### PR TITLE
options in transport_options was not being respected. Fix it

### PR DESCRIPTION
**Pull request by glennmatthews**
Fix making it possible to use options such as `prefix`, like the following
````
with_machine_options :transport_options => {
  'ip_address' => '10.122.82.108',
  'username' => 'root',
  'options' => {
    'prefix' => 'sudo '
  },
````

### CODE REVIEW

**Comment by glennmatthews** [comment]
Reworked for chef-provisioning-ssh 0.0.7.

````
with_machine_options :transport_options => {
  :ip_address => '10.122.82.108',
  :username => 'root',
  :options => {
    :prefix => 'sudo '
  },
````

**Comment by glennmatthews** [comment]
@double-z Is there anything I can do to move this along?

Thanks,

Glenn

**Comment by glennmatthews** [comment]
@mattray

**Comment by double-z** [comment]
Hey glen,

This is fixed, along with a whole boatload of other things, in the current release candidate - 0.0.8.rc.1.

The full list of changes will be in the CHANGELOG for the full release, to get an idea in the meantime of what was changed you can take a look at #13 

My apologies for not responding earlier... wasn't ignoring just didn't have a chance to write back/knew it was fixed in my branch/getting it tested against a few things internal/day to day job tasks etc. added up to lost it in the storm. 

Fwiw though, this release is/should be pretty tight -- and forgiving with options as sanely as is prudent. The CHANGELOG and README will have the details after full release.

I'm going to close this, but thx a bunch for the PR; any assistance is much appreciated. Please in the future do not hesitate to point out/fix and PR issues; like I said, it's much appreciated.

Cheers,
Zack

**Comment by glennmatthews** [comment]
Thanks for the explanation - I agree, it looks like you fixed this in your pull along with a bunch of other stuff. No worries!

Glenn

**Pull request closed without merging**
